[package]
name = "transcoder"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.4"
clap = { version = "4.3.10", features = ["derive"] }
color-eyre = "0.6.2"
indicatif = { version = "0.17.5", features = ["rayon"] }
rayon = "1.7.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
tracing = "0.1.37"
tracing-indicatif = "0.3.4"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
walkdir = "2.3.3"
