CREATE TABLE IF NOT EXISTS video_files (
    "path" VARCHAR NOT NULL UNIQUE,
    duration DOUBLE PRECISION NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    file_size INTEGER NOT NULL,
    bitrate DOUBLE PRECISION NOT NULL,
    framerate DOUBLE PRECISION NOT NULL,
    codec VARCHAR NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS video_conversions (
    video_file_id INTEGER NOT NULL,
    original_codec VARCHAR NOT NULL,
    new_codec VARCHAR NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
